spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?useSSL=false&serverTimezone=UTC
    username: root
    password: #YOUR_PASSWORD#
  jpa:
    hibernate:
      ddl-auto: create

someParameter:
  value: 5463